version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-eks: circleci/aws-eks@2.1.2
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  build-and-push:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            pwd
            ls -la
            cd base/node/9.0.0/
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/circleci-vulhub:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/circleci-vulhub:$TAG

  deploy-to-eks:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: my_cluster
          aws-region: us-west-2
      - kubernetes/create-or-update-resource:
          resource-file: k8s-deployment.yml
          resource-name: deployment/your-app-name

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
      - deploy-to-eks:
          requires:
            - build-and-push
          filters:
            branches:
              only: main