version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-eks: circleci/aws-eks@2.1.2
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  build-and-push:
    parameters:
      dockerfile:
        type: string
        default: "Dockerfile"
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: ${ECR_REPOSITORY_NAME}
          region: AWS_REGION
          tag: ${CIRCLE_SHA1}
          dockerfile: << parameters.dockerfile >>

  deploy-to-eks:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${EKS_CLUSTER_NAME}
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file: k8s-deployment.yml
          resource-name: deployment/log4j-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          name: build-log4j
          dockerfile: "log4j/CVE-2017-5645/Dockerfile"
          filters:
            branches:
              only: master
