version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
   #   - run:
   #       name: Run tests
   #       command: |
   #         docker-compose -f ./docker-compose.test.yml up
      - run:
          name: Build Docker image
          command: |
            pwd
            ls -la
            cd ./base/log4j/2.8.1/
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/circleci-vulhub:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/circleci-vulhub:$TAG